[package]
name = "fm"
version = "0.1.0"
edition = "2021"
authors = ["Andy Russell <arussell123@gmail.com>"]

[dependencies]
anyhow = "1.0.51"
chrono = "0.4.19"
clap = { version = "3.0.0-rc.7", features = ["derive"] }
env_logger = "0.9.0"
gio = "0.14.8"
humansize = "1.1.1"
libpanel = { git = "https://gitlab.gnome.org/euclio/libpanel-rs.git", branch = "fm" }
log = "0.4.14"
mime = "0.3.16"
pathdiff = "0.2.1"
relm4 = { git = "https://github.com/euclio/relm4", branch = "fm", features = ["libpanel"] }
relm4-macros = { git = "https://github.com/euclio/relm4", branch = "fm" }

[patch."https://github.com/gtk-rs/gtk-rs-core"]
gio = "0.14.8"
gio-sys = "0.14.0"
glib = "0.14.8"
glib-sys = "0.14.0"
gobject-sys = "0.14.0"
gtk-sys = "0.14.0"

[patch."https://github.com/gtk-rs/gtk4-rs"]
gdk4 = "0.3.1"
gtk4 = "0.3.1"
gtk4-sys = "0.3.1"
gdk4-sys = "0.3.1"

[patch."https://gitlab.gnome.org/World/Rust/libadwaita-rs"]
libadwaita = "0.1.0-beta-1"
libadwaita-sys = "0.1.0-beta-1"
