[package]
name = "fm"
version = "0.1.0"
edition = "2021"
authors = ["Andy Russell <arussell123@gmail.com>"]
publish = false
license = "MIT"

[dependencies]
anyhow = "1.0.51"
adw = { version = "0.1", package = "libadwaita" }
chrono = "0.4.19"
clap = { version = "3.0.0-rc.7", features = ["derive"] }
directories = "4.0.1"
env_logger = "0.9.0"
humansize = "1.1.1"
panel = { version = "0.1.0-alpha-0", package = "libpanel" }
log = "0.4.14"
mime = "0.3.16"
once_cell = "1.9.0"
pathdiff = "0.2.1"
relm4 = { version = "0.4.3", features = ["libpanel"] }
relm4-macros = "0.4.3"
relm4-components = "0.4.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sourceview5 = "0.4.0"
